version: '3.3'

services:
  #service 1: definition of mysql database
  rabbitmqa:
    image: rabbitmq:3-management
    container_name: rabbitmqa
    restart: always
    ports:
      - "15672:15672"
      - "5672:5672"

  #service 3: definition of your spring-boot app
  orderservice:                        #it is just a name, which will be used only in this file.
    image: app               #name of the image after dockerfile executes
    build:
      context: .                          #docker file path (. means root directory)
      dockerfile: Dockerfile              #docker file name
    ports:
      - "8090:8090"                       #docker containter port with your os port
    restart: always
    environment:
      - SPRING_RABBITMQ_HOST=rabbitmqa
    depends_on:                           #define dependencies of this app
      - rabbitmqa                                #dependency name (which is defined with this name 'db' in this file earlier)